version: '3'
services:
  server:
    env_file: ./env
    build: ./build
    image: ldotlopez/agate

    container_name: $NAME
    restart: unless-stopped

    ports:
      - $PORT:1965

    volumes:
      - $CONTENT:/content
