# gstreamer-rtsp (client plugins) are not available on alpine
FROM alpine

RUN apk \
    add --no-cache \
    gst-plugins-bad \
    gst-plugins-good \
    gst-plugins-ugly \
    gstreamer-tools \
    libcamera-gstreamer \
    libcamera-raspberrypi \
    libcamera-tools  \
    libcamera-v4l2 \
    v4l-utils
