version: '3'
services:
  vlc_telnet:
    env_file: ./env
    build: ./build
    image: ldotlopez/vlc-telnet

    container_name: "$NAME"
    restart: unless-stopped

    devices:
      - /dev/snd

    ports:
      - $PORT:4212

    volumes:
      - $CONFIG:/app/.config"
