version: '3'
services:
  vlc_telnet:
    env_file: env
    build: .
    image: ldotlopez/vlc-telnet
    container_name: $NAME
    restart: unless-stopped
    volumes:
      - ${CONFIG}:/app/.config
    devices:
      - /dev/snd
    ports:
      - ${PORT}:${VLC_PORT}
